#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/98a66433-97f9-4029-80bf-14f48924153b 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  CloudSwitch pIN_18;
  CloudSwitch pIN_19;
  CloudSwitch pIN_2;
  CloudSwitch pIN_21;
  CloudSwitch pIN_4;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 
  pinMode(2,OUTPUT);
  pinMode(4,OUTPUT);
  pinMode(21,OUTPUT);
  pinMode(19,OUTPUT);
  pinMode(18,OUTPUT);
  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  
  
}

/*
  Since PIN2 is READ_WRITE variable, onPIN2Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onPIN2Change()  {
  // Add your code here to act upon PIN2 change
   if (pIN_2==1){
     digitalWrite(2,LOW);
   }
  if (pIN_2==0){
     digitalWrite(2,HIGH);
   }
}

/*
  Since PIN4 is READ_WRITE variable, onPIN4Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onPIN4Change()  {
  // Add your code here to act upon PIN4 change
   if (pIN_4==1){
     digitalWrite(4,LOW);
   }
  if (pIN_4==0){
     digitalWrite(4,HIGH);
   }
}


/*
  Since PIN18 is READ_WRITE variable, onPIN18Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onPIN18Change()  {
  // Add your code here to act upon PIN18 change
   if (pIN_18==1){
     digitalWrite(18,LOW);
   }
  if (pIN_18==0){
     digitalWrite(18,HIGH);
   }
}


/*
  Since PIN19 is READ_WRITE variable, onPIN19Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onPIN19Change()  {
  // Add your code here to act upon PIN19 change
    if (pIN_19==1){
     digitalWrite(19,LOW);
   }
  if (pIN_19==0){
     digitalWrite(19,HIGH);
   }
}

/*
  Since PIN21 is READ_WRITE variable, onPIN21Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onPIN21Change()  {
  // Add your code here to act upon PIN21 change
  if (pIN_21==1){
     digitalWrite(21,LOW);
   }
  if (pIN_21==0){
     digitalWrite(21,HIGH);
   }
}
