// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "e0cfc254-4331-433e-bbbb-919a47c2814e";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onPIN18Change();
void onPIN19Change();
void onPIN2Change();
void onPIN21Change();
void onPIN4Change();

CloudSwitch pIN_18;
CloudSwitch pIN_19;
CloudSwitch pIN_2;
CloudSwitch pIN_21;
CloudSwitch pIN_4;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(pIN_18, READWRITE, ON_CHANGE, onPIN18Change);
  ArduinoCloud.addProperty(pIN_19, READWRITE, ON_CHANGE, onPIN19Change);
  ArduinoCloud.addProperty(pIN_2, READWRITE, ON_CHANGE, onPIN2Change);
  ArduinoCloud.addProperty(pIN_21, READWRITE, ON_CHANGE, onPIN21Change);
  ArduinoCloud.addProperty(pIN_4, READWRITE, ON_CHANGE, onPIN4Change);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
